version: '3.2'

services:
  go-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $PWD:/go/src/target
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - "127.0.0.1${PORT}${PORT}"
    restart: on-failure
  
  db:
    image: postgres:12.12
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db-assm-test
    restart: on-failure
    ports:
      - 5432:5432